
all:get glide vendor install linter test run

get:
	curl https://glide.sh/get | sh

glide:
	glide update

vendor:
	govendor sync update

install:
	gometalinter.v2 --install

linter:
	-gometalinter.v2 --vendor --tests --skip=mocks \
		--exclude='_gen.go' --exclude='docs.go' \
		--disable=gotype --disable=errcheck --disable=gas --disable=dupl \
		--deadline=1500s --checkstyle --sort=linter ./... > static-analysis.xml
test:
	-go test -v -cover ./... > tests.xml

build:
	go build -o gotoboox

run:
	go run main.go

prof:
	cd src/services
	go test -v -run=^$ -bench=^BenchmarkCommentsService_BookCommentsHandler$ -benchtime=2s -cpuprofile=prof.cpu
	go tool pprof services.test prof.cpu
